# Generated by Django 2.1.7 on 2019-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tweet_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
