# Generated by Django 2.1.7 on 2019-03-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_user_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='first_received_date',
        ),
        migrations.AddField(
            model_name='tweet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
