# Generated by Django 2.1.7 on 2019-03-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_tweet_full_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="monitored",
            field=models.BooleanField(default=True),
        ),
    ]
