# Generated by Django 2.1.7 on 2019-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190309_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hibernated',
            field=models.BooleanField(default=False),
        ),
    ]
