# Generated by Django 2.2.5 on 2020-01-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190408_1838'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['user', 'deleted', '-modified_date'], name='tracker_twe_user_id_000811_idx'),
        ),
    ]
