# Generated by Django 2.2.5 on 2020-03-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_auto_20200325_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="full_text",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
    ]
