# Generated by Django 2.1.7 on 2019-03-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_tweet_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='priority',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
