# Generated by Django 2.2.15 on 2020-08-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200325_1626'),
        ('tracker', '0008_auto_20200220_1806'),
    ]

    operations = [
    ]
