# Generated by Django 2.1.7 on 2019-03-10 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_tweet_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='added_date',
        ),
        migrations.AddField(
            model_name='user',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
