# Generated by Django 3.2.7 on 2021-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_auto_20200821_1814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="full_data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_data",
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(
                fields=["user", "-tweet_id"], name="tracker_twe_user_id_214516_idx"
            ),
        ),
    ]
