# Generated by Django 3.2.7 on 2021-09-13 02:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_auto_20210912_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="tracker_twe_search__6e13d2_gin"
            ),
        ),
    ]
