# Generated by Django 3.2.7 on 2021-09-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_auto_20210913_0223"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="deleted_time",
            field=models.DateTimeField(null=True),
        ),
    ]
